version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/saas-landing-page
    overwrite: yes

hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: ubuntu
